config/routes.rb
Rails.application.routes.draw do
  root 'snacks#index'
  resources :snacks, only: [:index, :new, :create, :update]
  get '/snacks/vote', to: 'snacks#vote', as: 'votes_snacks'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/snack_api.rb
# class SnackAPI
#   include HTTParty
#   base uri 'https://api-snacks.nerderylabs.com/v1/'
#   SNACK_ACCESS = "/snacks?ApiKey=#{ENV['SNACK_API_KEY']}"
#
#   def get_snacks
#     response = self.class.get(SNACK_ACCESS)
#     JSON.parse(response.body)
#   end
# end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/snacks_controller.rb
class SnacksController < ApplicationController
  def index
    snack_api = SnackAPI.new
    snack_api.get_snacks
    @permanent_snacks = snack_api.where(optional: false)
    @optional_snacks = snack_api.where(optional: true)
    #initiate session reset
    reset
  end

  def new
    snack_api = SnackAPI.new
    snack_api.get_snacks
    @optional_snacks = snack_api.where(optional: true)
  end

  def create
    num_of_suggestions = session['num_of_suggestions'] || 0
    # check if user has made a suggestion
    if num_of_suggestions >= 1
      flash[:notice] = "You have already made a suggestion for this month...Please wait until next month"
    else
      snack_api = SnackAPI.new
      snack_api.post_snacks(params)
      # Add user suggestion to session for the number of suggestions made
      num_of_suggestions += 1
      flash[:notice] = "Your suggestion has been submitted"
    end
    session['num_of_suggestions'] = num_of_suggestions
    redirect_to root_path
  end
  # Used sessions instead of cookies for security
  def vote
    snack_votes = session['total_votes'] || 0
    # checks user vote count
    if snack_votes >= 3
      # user has voted max amount of time
      flash[:notice] = "You've voted the maximum number of times for the month"
    else
      snack_votes += 1
      # lets user know his/her vote has been recorderd
      flash[:notice] = "Vote has been recorded"
    end
    session['total_votes'] = snack_votes
    redirect_to root_path
  end

  def reset
    request.session_options[:expires_at] = 1.month.from_now
    #session[:expires_at] = Time.now + 1.month
  end



end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/snacks_helper.rb
module SnacksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SnaFoo</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <nav class="navbar navbar-toggleable-md navbar-light bg-faded">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <%= link_to "SnaFoo", root_path, :class => 'navbar-brand' %>

    <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
      <ul class="navbar-nav mr-auto mt-2 mt-md-0">
        <li class="nav-item">
          <%= link_to "Suggestions", new_snack_path, :class => 'nav-link' %>
        </li>
      </ul>
    </div>
  </nav>

    <br class="clear" />

    <%= yield %>

  </body>
</html>

app/views/snacks/index.html.erb
<h1 class='text-center'> Welcome to SnaFoo! </h1>

<br />

<h5 class='text-center'> Permanent Snacks: </h5>

<br class='clear'/>

<!-- Non-Optional Snacks -->
<div class='col-3 perm'>
  <ul class='list-group'>
    <% @permanent_snacks.each do |snack| %>
      <li class='list-group-item'>
        <%= snack["name"] %>
      </li>
    <% end %>
  </ul>
</div>

<br  />

<h5 class='text-center'> Suggested Snacks: </h5>

<h6 class='text-center'> Vote for the snacks you want to see this month! </h6>

<h7 class='votes-rem'> Votes Remaining = <%= 3 - (session['total_votes'] || 0) %> </h7>

<br class='clear' />
<br  />

<!-- Displays error messages -->
<div class='container text-center'>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>

<!-- Suggested/Votable snacks -->
<div class='text-center'>
  <% @optional_snacks.each do |snack| %>
    <%= snack["name"] %>
    <%= snack["last_purchased"] %>
    <%= link_to "Vote", votes_snacks_path, class: 'btn btn-secondary' %>
    <br  />
  <% end %>
</div>

<br  />
<br  />

<h4 class='text-center'> Don't see anything you like? </h5>

<br  />

<div class='text-center'>
  <%= link_to "Make a suggestion", new_snack_path, :class => 'btn btn-lg btn-secondary' %>
</div>

<br  />
<br  />

app/views/snacks/new.html.erb
<h2 class='text-center'> Make suggestions for this months snacks! </h3>

<br  />

<!-- Dropdown Menu for previously suggested snacks -->
<div class='suggestions_form text-center'>
  <div class="btn-group">
    <button class="btn btn-secondary btn-lg dropdown-toggle" type="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      Suggest from previous snacks
    </button>
    <div class="dropdown-menu">
      <% @optional_snacks.each do |snack| %>
        <%= link_to snack['name'], root_path, class: 'dropdown-item' %>
      <% end %>
    </div>
  </div>

<br  />
<br  />

<!-- Form to suggest snacks -->
  <%= form_tag('/snacks', method: :post) do %>
      <div class="form-group">
        <label for="">Snack Suggestion:</label>
        <input type="text" class="form-control" id="" aria-describedby="" placeholder="Enter suggestion" name='name'>
      </div>
      <div class="form-group">
        <label for="">Purchase Location:</label>
        <input type="text" class="form-control" id="" placeholder="Enter location" name='purchase_location'>
      </div>
      <div class="form-check">
      </div>
      <button type="submit" class="btn btn-secondary">Submit</button>
  <% end %>
</div>

<div class='container text-center'>
  <% flash.each do |key, value| %>
      <div class="alert alert-<%= key %>"><%= value %></div>
  <% end %>
</div>